name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force XCode 11.5
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
